# Generated by Django 4.1.7 on 2023-03-04 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_doctor_clinics_doctor_expertises_receptionist_clinic"),
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="nom")),
                ("start", models.DateTimeField(verbose_name="date de début")),
                ("end", models.DateTimeField(verbose_name="date de fin")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Inconnu"),
                            (2, "Planifie"),
                            (3, "En Attente"),
                            (4, "En cours"),
                            (5, "Terminé"),
                            (6, "Annulé"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("note", models.CharField(max_length=2048, verbose_name="note")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
            ],
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="Appointement",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "note_pre_appointement",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="note pré rendez-vous ",
                    ),
                ),
                (
                    "note_post_appointement",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="note après le rendez-vous",
                    ),
                ),
                (
                    "waiting_examination",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Dans la salle d'attente",
                    ),
                ),
                (
                    "start_examination",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Début de l'examen",
                    ),
                ),
                (
                    "end_examination",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fin de l'examen",
                    ),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, verbose_name="envoyer sms rappel"),
                ),
                (
                    "send_email",
                    models.BooleanField(default=False, verbose_name="envoyer email rappel"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_appointements",
                        to="clinic.clinic",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_appointements",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_appointements",
                        to="accounts.patient",
                    ),
                ),
            ],
            bases=("events.event",),
        ),
    ]
