# Generated by Django 4.1.3 on 2022-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointement",
            name="end_examination",
            field=models.DateTimeField(default=None, verbose_name="Fin de l'examen"),
        ),
        migrations.AddField(
            model_name="appointement",
            name="start_examination",
            field=models.DateTimeField(default=None, verbose_name="Début de l'examen"),
        ),
        migrations.AddField(
            model_name="appointement",
            name="waiting_examination",
            field=models.DateTimeField(default=None, verbose_name="Dans la salle d'attente"),
        ),
    ]
