version: "3.3"
services:
  http:
    image: rachadoc/backend
    build: .
    restart: always
    command: bash -c "pipenv run manage collectstatic --noinput && pipenv run manage migrate --noinput && pipenv run gunicorn --preload --bind=0.0.0.0:8000 --workers=4 --timeout=300 --graceful-timeout=150 --log-level=INFO rachadoc.core.wsgi"
    ports:
      - 8000:8000
    env_file:
      - ./rachadoc/core/settings/.env
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - static_data:/projects/rachadoc/rachadoc/staticfiles
    expose:
      - 8000

  postgres:
    image: postgis/postgis:14-master
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./rachadoc/core/settings/.env
    networks:
      - backend
    expose:
      - "5432"
  
  redis:
    image: redis:7-alpine
    networks:
      - backend
    expose:
      - "6379"
  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static/
    ports:
      - "80:80"
    depends_on:
      - http
    networks:
      - backend
    
  websocket:
    build: .
    command: pipenv run daphne -b 0.0.0.0 -p 9000 rachadoc.core.asgi:application
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - http
    expose:
      - 9000
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  static_data:

networks:
  backend: