# Generated by Django 4.2 on 2023-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointementnotification",
            name="status",
            field=models.IntegerField(
                choices=[
                    (2, "Livré"),
                    (4, "Échec de la livraison"),
                    (3, "Désengagement"),
                    (1, "Programmé"),
                    (5, "Desactiver"),
                ]
            ),
        ),
    ]
