# Generated by Django 4.1.7 on 2023-03-04 23:28

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_doctor_clinics_doctor_expertises_receptionist_clinic"),
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_day",
                    models.IntegerField(
                        choices=[
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Vendredi"),
                            (6, "Samedi"),
                            (7, "Dimanche"),
                        ],
                        default=1,
                        verbose_name="jour de semaine",
                    ),
                ),
                ("from_date", models.TimeField(verbose_name="heure de début")),
                ("to_date", models.TimeField(verbose_name="heure de fin")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorAgendaSetting",
            fields=[
                (
                    "agendasetting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="agendasetting.agendasetting",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
            ],
            bases=("agendasetting.agendasetting", rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="ClinicAgendaSetting",
            fields=[
                (
                    "agendasetting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="agendasetting.agendasetting",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinic.clinic"),
                ),
            ],
            bases=("agendasetting.agendasetting", rules.contrib.models.RulesModelMixin),
        ),
    ]
