# Generated by Django 4.1.3 on 2022-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendasetting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendasetting",
            name="from_date",
            field=models.TimeField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="agendasetting",
            name="to_date",
            field=models.TimeField(verbose_name="date de fin"),
        ),
    ]
