# Generated by Django 4.1.3 on 2022-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendasetting", "0002_alter_agendasetting_from_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendasetting",
            name="from_date",
            field=models.TimeField(verbose_name="heure de début"),
        ),
        migrations.AlterField(
            model_name="agendasetting",
            name="to_date",
            field=models.TimeField(verbose_name="heure de fin"),
        ),
    ]
