# Generated by Django 4.1.3 on 2022-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="address",
            field=models.CharField(max_length=1024, verbose_name="addresse"),
        ),
    ]
