# Generated by Django 4.1.1 on 2022-11-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("clinic", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="clinics",
            field=models.ManyToManyField(through="common.Tarif", to="clinic.clinic"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="expertises",
            field=models.ManyToManyField(to="common.expertise"),
        ),
    ]
