# Generated by Django 4.1.7 on 2023-03-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
        ("common", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="clinics",
            field=models.ManyToManyField(through="common.Tarif", to="clinic.clinic"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="expertises",
            field=models.ManyToManyField(to="common.expertise"),
        ),
        migrations.AddField(
            model_name="receptionist",
            name="clinic",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
            preserve_default=False,
        ),
    ]
