# Generated by Django 4.2 on 2023-04-30 20:37

from django.db import migrations
import rachadoc.accounts.managers


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_doctor_clinics_doctor_expertises_receptionist_clinic"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="doctor",
            managers=[
                ("objects", rachadoc.accounts.managers.DoctorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patient",
            managers=[
                ("objects", rachadoc.accounts.managers.PatientManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="receptionist",
            managers=[
                ("objects", rachadoc.accounts.managers.ReceptionistManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", rachadoc.accounts.managers.BaseUserManager()),
            ],
        ),
    ]
