# Generated by Django 4.1.3 on 2022-12-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctor_clinics_doctor_expertises"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="receptionist",
            options={},
        ),
    ]
