# Generated by Django 4.1.7 on 2023-03-04 23:17

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="description"),
                ),
            ],
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="description"),
                ),
                ("amount", models.FloatField(verbose_name="montant")),
                (
                    "clinic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinic.clinic"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
            ],
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=1024, verbose_name="description"),
                ),
                ("url", models.URLField()),
                (
                    "clinic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinic.clinic"),
                ),
            ],
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
    ]
